config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => {
			confirmations: 'users/confirmations'
	}
	#
	#
	get 'pins/index'
 	# 
	resources :pins do
		resources :likes
	end

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	get '/show/:id', to: 'home#show', as: 'show'


	get 'home/index'

	get 'pins/index'
	root 'home#index'
end

app/models/pin.rb
class Pin < ApplicationRecord
	has_one_attached :image
	belongs_to :user
	has_many :likes, dependent: :destroy
	
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
    load_and_authorize_resource param_method: :my_sanitizer
 #   skip_authorize_resource :only => [:index, :show]
    #before_action :set_pin, only: [:show, :edit, :update, :destroy]

    # GET /pins
    # GET /pins.json
    def index
        @apins = Pin.where(user_id: current_user.id)
        @pins = Pin.where(user_id: current_user.id).paginate(page: params[:page], per_page: 8)
          .order(updated_at: :desc)
        #    @pins = Pin.where(user_id: current_user.id).order(updated_at: :desc)
    end

    # GET /pins/1
    # GET /pins/1.json
    def show
    end

    # GET /pins/new
    def new
        @pin = Pin.new
    end

    # GET /pins/1/edit
    def edit
    end

    # POST /pins
    # POST /pins.json
    def create

        @pin = current_user.pin.new(pin_params)
        @pin.image.attach(params[:pin][:image])

        respond_to do |format|
            if @pin.save
                format.html { redirect_to @pin, notice: t('activerecord.helpers.pin.created') }
                format.json { render :show, status: :created, location: @pin }
            else
                format.html { render :new }
                format.json { render json: @pin.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /pins/1
    # PATCH/PUT /pins/1.json
    def update
        respond_to do |format|
            if @pin.update(pin_params)
                format.html { redirect_to @pin, notice: t('activerecord.helpers.pin.updated') }
                format.json { render :show, status: :ok, location: @pin }
            else
                format.html { render :edit }
                format.json { render json: @pin.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /pins/1
    # DELETE /pins/1.json
    def destroy
        @upload = @pin.image
        @pin.destroy
        @upload.purge_later
        respond_to do |format|
            format.html { redirect_to pins_url, notice: t('activerecord.helpers.pin.destroyed') }
            format.json { head :no_content }
        end
    end

    private

    def my_sanitizer
        params.require(:pin).permit(:title, :description, :image)
    end

    def pin_params
        params.require(:pin).permit(:title, :description, :likes, :image)
    end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= form_with(model: pin, local: true, :html => {class: 'form'}) do |form| %>
<% if pin.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>
        <ul>
        <% pin.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

    <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, placeholder: true, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :description %>
        <%= form.trix_editor :description %>
    </div>

    <div class="form-group">
        <%= form.label :image %>
        <%= form.file_field :image, class: 'd-block' %>
    </div>

    <% if pin.image.attached? %>
    <div class="form-group">
        <%= image_tag pin.image, class: 'card-img-top wt-200' %>
    </div>
    <% end %>

    
    <div class="form-group">
        <%= form.submit t('shared.create') + ' Pin', class: 'btn btn-primary'%>
    </div>
<% end %>

app/views/pins/_pinsindex.html.erb
<div class="card card-pt" style="margin-bottom:50px !important">
	<% if pin.image.attached? %>
 	<%= image_tag pin.image, class: 'card-img-top foto' %>
 	<% end %>
 	<div class="card-body">
 		<div class="text-right">
			<%= pin.user.username%> |
			<span id="likes-<%= pin.id %>"><%= pin.likes.count %></span>
			<%	pre_like = pin.likes.find { |like| like.user_id == current_user.id} %>
			<% 	if pre_like %>
			<i class="fas fa-heart rojo cursor-pointer like" data-icon="fas" data-id="<%= pin.id %>" data-lid="<%= pre_like.id %>"></i>
			<% 	else %>
			<i class="far fa-heart rojo cursor-pointer like" data-icon="far" data-id="<%= pin.id %>" data-lid=""></i>
			<% 	end %>
		</div>
		<div>
			<h4 class="card-title"><%= pin.title %></h4>
 		</div>
	</div>
	<div class="card-footer">
		<div class="text-center">
			<%= link_to t('shared.view'), pin_path(:id => pin.id), class: 'btn btn-info'%>
			<%= link_to t('shared.edit'), edit_pin_path(:id => pin.id), class: 'btn btn-warning'%>
			<%= link_to t('shared.delete'), {controller: "pins", action: "destroy", id: pin}, method: 'delete', data: { confirm: t('shared.confirm') }, class: 'btn btn-primary' %>
		</div>
	</div>
</div>

app/views/pins/edit.html.erb
<h1><%= t('.title') %></h1>
<%= link_to raw('<i class="fas fa-angle-double-left"></i> ') + t('shared.back'), pins_path, class: 'btn btn-outline-primary mb-3' %>

<%= render 'form', pin: @pin %>

app/views/pins/index.html.erb
<h1 style="display: inline-block;">
	<%= current_user.first_name.titleize + ' ' + current_user.last_name.titleize %> 
</h1>
<div >
    <%= link_to raw('<i class="fas fa-2x fa-plus-square"></i>'), new_pin_path %> 
    <%= link_to raw('<i class="fas fa-2x fa-pen-square"></i>'), edit_user_registration_path %>
</div>
<div class="mb-3">
    <i><%= @apins.size %> Pin's <%= current_user.username%></i></i>
</div>



    
<div class="card-deck" id="pins">
    <%= render partial: 'pins/pinsindex', collection: @pins, as: :pin %>
</div>
<div class="text-center">
    <%= will_paginate @pins %>
</div>

app/views/pins/index.js.erb
$('#pins').append('<%= j render partial: 'pins/pinsindex', collection: @pins, as: :pin %>');

<% if @pins.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate @pins%>');	
<% else %>
	$('.pagination').remove();
<% end %>

app/views/pins/new.html.erb
<h1><%= t('.title') %></h1>


<%= link_to raw('<i class="fas fa-angle-double-left"></i> ') + t('shared.back'), pins_path, class: 'btn btn-outline-primary mb-3' %>


<%= render 'form', pin: @pin %>

app/views/pins/show.html.erb
<%= link_to raw('<i class="fas fa-2x fa-arrow-left"></i>'), pins_path, class: 'btn btn-primary pull-left'%>



<div class="row">
	<div class="offset-4 col-4">
		<div class="card">
			<% if @pin.image.attached? %>
	 		<%= image_tag @pin.image, class: 'card-img-top' %>
	 		<% end %>
		 	<div class="card-body">
				<div class="text-right">
					<% if user_signed_in? %>
						<%= @pin.user.username%> | 
						<span id="likes-<%= @pin.id %>"><%= @pin.likes.count %></span>
						<%	pre_like = @pin.likes.find { |like| like.user_id == current_user.id} %>
						<% 	if pre_like %>
						<i class="fas fa-heart rojo cursor-pointer like" data-icon="fas" data-id="<%= @pin.id %>" data-lid="<%= pre_like.id %>"></i>
						<% 	else %>
						<i class="far fa-heart rojo cursor-pointer like" data-icon="far" data-id="<%= @pin.id %>" data-lid=""></i>
						<% 	end %>
						<% 	end %>
				</div>
		 		<div>
					<h4 class="card-title"><%= @pin.title %></h4>
		 		</div>
		 		<% if user_signed_in? %>
		 		<div class="card-text">
		 			<%= @pin.description.html_safe %>
		 		</div>


				<% if @pin.user.id == current_user.id %>
			 	<div class="mt-5 text-center">
					<%= link_to t('shared.edit'), edit_pin_path(:id => @pin.id), class: 'btn btn-warning'%>
					<%= link_to t('shared.delete'), {controller: "pins", action: "destroy", id: @pin}, method: 'delete', data: { confirm: t('shared.confirm') }, class: 'btn btn-primary' %>
				</div>
				<% end%>
				<% end %>

		 	</div>
		</div>
	</div>
</div>

<br/><br/><br/>